--- #YAML:1.0
name:               Cisco-EEM-RPC
version:            1.0.1
abstract:           Perl interface to EEM RPC
author:
    - Joe Marcus Clarke <jclarke@cisco.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    Net::SSH::Perl:  1.00
    XML::LibXML:     0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
